# Generated by Django 5.0.4 on 2024-05-08 23:49

import binnacleNSO.models
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Sub usuario')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='media/usersPhotos/default.jpg', force_format='JPEG', keep_meta=False, quality=75, scale=0.5, size=[200, 200], upload_to=binnacleNSO.models.UploadToPathAndRename('media/usersPhotos'), verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Subuser',
                'verbose_name_plural': 'Subusers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Super usuario')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Racha')),
                ('numberOfEntries', models.PositiveIntegerField(default=0, verbose_name='Numero de entradas')),
                ('lastEntryDate', models.DateField(blank=True, null=True, verbose_name='Ultima entrada')),
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='Contenido')),
                ('stars', models.PositiveIntegerField(default=1, verbose_name='Estrellas')),
                ('shares', models.PositiveIntegerField(default=1, verbose_name='Retweets')),
                ('image', models.ImageField(blank=True, null=True, upload_to=binnacleNSO.models.UploadToPathAndRename('media/entriesPhotos'), verbose_name='Imagen')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='Numero de entrada')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='binnacleNSO.alias')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='binnacleNSO.profile')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.AddField(
            model_name='alias',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='binnacleNSO.profile'),
        ),
    ]
