# Generated by Django 5.0.4 on 2024-04-20 21:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/usersPhotos'), upload_to='')),
            ],
            options={
                'verbose_name': 'Subuser',
                'verbose_name_plural': 'Subusers',
            },
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Super usuario')),
                ('streak', models.PositiveIntegerField(verbose_name='Racha')),
                ('numberOfEntries', models.PositiveIntegerField(default=0, verbose_name='Numero de entradas')),
                ('lastEntryDate', models.DateField(default=None, verbose_name='Ultima entrada')),
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
            },
        ),
    ]
