# Generated by Django 5.0.4 on 2024-05-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name': 'Alias', 'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.alias'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
    ]
