# Generated by Django 5.0.4 on 2024-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='name',
            field=models.CharField(default='owo', max_length=40, unique=True, verbose_name='Super usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image',
            field=models.ImageField(upload_to='media/usersPhotos'),
        ),
    ]
