# Generated by Django 5.0.4 on 2024-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0002_subuser_name_alter_subuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Sub user'),
        ),
    ]
