# Generated by Django 5.0.4 on 2024-04-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0003_alter_subuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='superuser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.superuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superuser',
            name='streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha'),
        ),
    ]
