# Generated by Django 5.0.4 on 2024-04-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0004_subuser_superuser_alter_superuser_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='Contenido')),
                ('stars', models.PositiveIntegerField(default=1, verbose_name='Estrellas')),
                ('shares', models.PositiveIntegerField(default=1, verbose_name='Retweets')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/entriesPhotos', verbose_name='Imagen')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='Numero de entrada')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image',
            field=models.ImageField(default='media/usersPhotos/default.jpg', upload_to='media/usersPhotos', verbose_name='Imagen'),
        ),
    ]
