# Generated by Django 5.0.4 on 2024-04-20 23:11

import binnacleNSO.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0005_entry_alter_subuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=binnacleNSO.models.UploadToPathAndRename('entriesPhotos'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image',
            field=models.ImageField(default='media/usersPhotos/default.jpg', upload_to=binnacleNSO.models.UploadToPathAndRename('usersPhotos'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Sub usuario'),
        ),
    ]
