# Generated by Django 5.0.4 on 2024-04-20 23:38

import binnacleNSO.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0006_alter_entry_image_alter_subuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='subuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.subuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.PositiveIntegerField(verbose_name='Numero de entrada'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=binnacleNSO.models.UploadToPathAndRename('media/entriesPhotos'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image',
            field=models.ImageField(default='media/usersPhotos/default.jpg', upload_to=binnacleNSO.models.UploadToPathAndRename('media/usersPhotos'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to='binnacleNSO.superuser'),
        ),
    ]
