# Generated by Django 5.0.4 on 2024-04-21 18:26

import binnacleNSO.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0007_entry_subuser_alter_entry_day_alter_entry_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='availableEntries',
            field=models.PositiveIntegerField(default=1, verbose_name='Entradas disponibles'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero de entrada'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/usersPhotos/default.jpg', force_format='JPEG', keep_meta=False, quality=75, scale=0.5, size=[200, 200], upload_to=binnacleNSO.models.UploadToPathAndRename('media/usersPhotos'), verbose_name='Imagen'),
        ),
    ]
