# Generated by Django 5.0.4 on 2024-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0008_superuser_availableentries_alter_entry_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='lastEntryDate',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima entrada'),
        ),
    ]
