# Generated by Django 5.0.4 on 2024-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0009_alter_superuser_lastentrydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='availableEntries',
        ),
    ]
