# Generated by Django 5.0.4 on 2024-04-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0010_remove_superuser_availableentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='subuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subuser', to='binnacleNSO.subuser'),
        ),
    ]
