# Generated by Django 5.0.4 on 2024-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0011_alter_entry_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='password',
            field=models.CharField(default='owo', max_length=50, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
