# Generated by Django 5.0.4 on 2024-04-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0012_superuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='superuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.superuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='subuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.subuser'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binnacleNSO.superuser'),
        ),
    ]
