# Generated by Django 5.0.4 on 2024-04-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0013_entry_superuser_alter_entry_subuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='subuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='binnacleNSO.subuser'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='binnacleNSO.superuser'),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='superuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superuser', to='binnacleNSO.superuser'),
        ),
    ]
