# Generated by Django 5.0.4 on 2024-04-28 19:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binnacleNSO', '0014_superuser_is_authenticated_alter_entry_subuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='superuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='superuser',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anónimo'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Autenticado'),
        ),
    ]
