# Generated by Django 5.0.4 on 2024-04-19 00:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(max_length=200, verbose_name='Descripción')),
                ('dueDate', models.DateTimeField(default=datetime.datetime(2024, 4, 19, 18, 30, 40, 816569), verbose_name='Fecha limite')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Completada')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Materia')),
                ('teacher', models.CharField(max_length=100, verbose_name='Maestro')),
            ],
        ),
        migrations.CreateModel(
            name='PTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks_scheduler.task')),
                ('priority', models.CharField(choices=[('UR', 'Urgente'), ('HG', 'Alta'), ('MD', 'Media'), ('LW', 'Baja')], default='LW', max_length=2, verbose_name='Prioridad')),
            ],
            bases=('tasks_scheduler.task',),
        ),
        migrations.CreateModel(
            name='WSTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks_scheduler.task')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_scheduler.subject')),
            ],
            bases=('tasks_scheduler.task',),
        ),
    ]
